from .config import MediaType
from typing import TypedDict

class CensusEntry(TypedDict):
    hash: str
    dir_path: str

def get_require_path(pattern: str): ...
def extract_library_statements(input_string: str, library_var_name: str): ...
def get_used_paths(is_verbose: bool = ...) -> dict[MediaType, list[str]]: ...
def update_lock_data(usage_registry: dict[MediaType, list[str]] = ..., reset_unused: bool = ...) -> dict[str, str]: ...
