from .util import AssetData as AssetData, expand_into_directory as expand_into_directory, get_file_hash as get_file_hash, group_directory as group_directory

def build_animation(asset_data: AssetData, build_path: str, is_verbose: bool): ...
def build_audio(asset_data: AssetData, build_path: str, is_verbose: bool, skip_upload: bool): ...
def build_image(asset_data: AssetData, build_path: str, is_verbose: bool, skip_upload: bool): ...
def build_material(asset_data: AssetData, build_path: str, is_verbose: bool): ...
def build_mesh(asset_data: AssetData, build_path: str, is_verbose: bool): ...
def build_model(asset_data: AssetData, build_path: str, is_verbose: bool): ...
def build_particle(asset_data: AssetData, build_path: str, is_verbose: bool): ...
